### ISSUE TITLE
Why the process doesn't exit while all task done? 

### ISSUE THREAD

**Issue by mike442144** [sylvinus/node-crawler#137]
I use node-crawler to crawl pages, but the process is always running even if all is done. What is the possible reason for this ? Thanks a lot.

**Comment by wegorich** [comment]
Maybe it's start like http server

**Comment by paulvalla** [comment]
will normally exit with a 0 status code when no more async operations are pending.
Can you share your code here or by email so I can have a look ?
Which version of node are you using ?

**Comment by mike442144** [comment]
@paulvalla Thank you for your replay, the code is quite simple but I append thousands of URLs to the queue, I'm wondering if pushing too many tasks since I've ran into that for several times. maybe I should dump the heap to see any error...

**Comment by mike442144** [comment]
@wegorich Thanks, I just use the crawler in normal node program rather than httpserver.
