### ISSUE TITLE
Why do I get string of result.body even when I set the encoding=null

### ISSUE THREAD

**Issue by mike442144** [sylvinus/node-crawler#141]
As the title says, why?

**Comment by mike442144** [comment]
Which should be a buffer said by the request document.

**Comment by mike442144** [comment]
I've read the source code I didn't find the reason but I solved my problem.

**Comment by Svenskunganka** [comment]
Hey, did you manage to solve this? Got the same issue :/

**Comment by mike442144** [comment]
@Svenskunganka This problem has not been solved yet. I read the source code but nothing seems incorrect.I'll double check the source code when I have enough time.

**Comment by paulvalla** [comment]
Can you provide me a url that you need to try and your code so i can have a look ?

**Comment by Svenskunganka** [comment]
@mike442144 alright, thank you.

@paulvalla Basically I'm crawling url's and downloading a file to be parsed, however the file has been converted to a string from the standard request Buffer output. Using request alone solves this, so I've been switching up my code a bit now so I don't really have anything to show you and hope that my description alone can help you understand the issue.

To break it down there is no way to get a Buffer returned from this package when requesting a binary file.

**Comment by mike442144** [comment]
I've solved this problem, please move to https://github.com/bda-research/node-webcrawler if you wanna continue using the crawler, Our team will maintain.
