### ISSUE TITLE
Can I take arguments that put in queue() function from callback? 

### ISSUE THREAD

**Issue by mike442144** [sylvinus/node-crawler#142]
Say, I have data related to each of the requests, that is one data to one request. So I want get data of each request once the callback fire up. But I cannot find any API about this routine, like 
 `crawler.queue({uri:"",callback:func,mydata:"this is my data of current request which could use in the callback when called"})`
 so can anybody help?

**Comment by Maxwell2022** [comment]
you can set whatever option you want and get access to it in the callback.

ie:

```coffeescript
callback = (error, result, $) ->
  # Do whatever you need here

  logger.info result.options.name + ' has been crawled !' + result.options.myOtherDummyOption
  return

for item in config.urls
  crawler.queue name: item.name, myOtherDummyOption: 'blah', uri: item.url, callback: callback
```

**Comment by nonzenz** [comment]
You can actually retrieve the info from this object also, which is useful in case of error (because then result is not returned):


callback: function(error, result, $) {
  console.log(this.uri)
  console.log(this.mydata)
}

**Comment by mike442144** [comment]
Thanks @Maxwell2022 @nonzenz As you guys said , It woks well for me.
