### ISSUE TITLE
how to crawler with the web page using ajax?

### ISSUE THREAD

**Issue by shikelong** [sylvinus/node-crawler#159]
thx.

**Comment by mike442144** [comment]
In crawler, you have to figure out the ajax URL and request one by one.

**Comment by mike442144** [comment]
@shikelong Please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it.

**Comment by shikelong** [comment]
thank you!
