### ISSUE TITLE
How about the HTML document that rendered by client script?

### ISSUE THREAD

**Issue by JerryC8080** [sylvinus/node-crawler#167]
After an overview of source code.
I found the `node-crawler` use `request` to make a http request.
But if the page i crawl that rendered by some client technology such as: AngularJS、ReactJS....
I may can't get the correct DOM of the page?

**Comment by scott-wyatt** [comment]
@JerryC8080 you would want to use Phantom JS for that.

**Comment by JerryC8080** [comment]
@scott-wyatt 
Ok, i am so sorry for this such lower question.
I just like the API of `node-crawler`.
